import os
import secrets
import threading
import time
import uuid

_RAND_A_BITS = 12
_RAND_A_MAX = (1 << _RAND_A_BITS) - 1
_RAND_B_MASK = (1 << 62) - 1
_TIMESTAMP_MASK = (1 << 48) - 1


class _UUID7Generator:
    """RFC 9562 UUIDv7 with a monotonic counter in `rand_a` (method 1).

    IDs generated by one process are strictly increasing, so ordering by
    primary key reproduces insertion order even within a single millisecond.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._last_timestamp_ms = 0
        self._counter = 0

    def __call__(self) -> uuid.UUID:
        with self._lock:
            timestamp_ms = time.time_ns() // 1_000_000
            if timestamp_ms > self._last_timestamp_ms:
                # Seed in the lower half so a burst has room to count up.
                self._counter = secrets.randbits(_RAND_A_BITS - 1)
            else:
                timestamp_ms = self._last_timestamp_ms
                self._counter += 1
                if self._counter > _RAND_A_MAX:
                    timestamp_ms += 1
                    self._counter = 0
            self._last_timestamp_ms = timestamp_ms
            counter = self._counter

        rand_b = int.from_bytes(os.urandom(8)) & _RAND_B_MASK
        value = (
            (timestamp_ms & _TIMESTAMP_MASK) << 80  # unix_ts_ms
            | 0x7 << 76  # version
            | counter << 64  # rand_a
            | 0b10 << 62  # variant
            | rand_b
        )
        return uuid.UUID(int=value)


uuid7 = _UUID7Generator()
