from datetime import UTC, datetime, timedelta

import pytest

from cortex_api.models.evidence_edge import EvidenceEdgeType
from cortex_api.models.evidence_node import EvidenceNodeType
from cortex_api.services.evidence.provenance import (
    Provenance,
    ProvenanceError,
    TimelineKind,
    api_source,
    clamp,
    decision_confidence,
    excerpt,
    occurred_at,
    phrase,
    timeline,
)

from .builders import EPOCH, GraphBuilder

NOW = datetime(2026, 9, 27, tzinfo=UTC)


class TestProvenance:
    def test_valid_provenance(self) -> None:
        provenance = Provenance(0.5, "Cited as [1]", "cortex.knowledge.citations", NOW)
        assert provenance.confidence == 0.5

    @pytest.mark.parametrize(
        ("confidence", "explanation", "source", "timestamp"),
        [
            (1.5, "why", "who", NOW),
            (-0.1, "why", "who", NOW),
            (float("nan"), "why", "who", NOW),
            (0.5, "   ", "who", NOW),
            (0.5, "why", "", NOW),
            (0.5, "why", "x" * 256, NOW),
            (0.5, "x" * 2001, "who", NOW),
            (0.5, "why", "who", datetime(2026, 9, 27)),
        ],
    )
    def test_nothing_is_anonymous_or_out_of_range(
        self, confidence: float, explanation: str, source: str, timestamp: datetime
    ) -> None:
        with pytest.raises(ProvenanceError):
            Provenance(confidence, explanation, source, timestamp)

    def test_now_clamps_confidence_and_stamps_utc(self) -> None:
        provenance = Provenance.now(3.2, "Recalled", "cortex.memory.recall")
        assert provenance.confidence == 1.0
        assert provenance.timestamp.tzinfo is not None

    def test_of_reads_an_edge(self) -> None:
        builder = GraphBuilder()
        builder.node("a")
        builder.node("b")
        edge = builder.edge("a", "b", confidence=0.4)
        provenance = Provenance.of(edge)
        assert (provenance.confidence, provenance.source) == (0.4, "test")
        assert provenance.timestamp == edge.observed_at

    def test_api_source_names_the_key(self) -> None:
        builder = GraphBuilder()
        key = builder.node("key").id
        assert api_source(key) == f"api:key/{key}"
        assert api_source(None) == "api:organization"


def test_clamp_and_excerpt() -> None:
    assert clamp(float("nan")) == 0.0
    assert clamp(-1) == 0.0
    assert clamp(0.25) == 0.25
    assert excerpt("  many\n  spaces  here ", 100) == "many spaces here"
    assert excerpt("abcdefghij", 5) == "abcd…"


class TestDecisionConfidence:
    def test_unsupported_decisions_score_zero(self) -> None:
        assert decision_confidence([]) == 0.0

    def test_supports_accumulate_as_noisy_or(self) -> None:
        assert decision_confidence([0.5]) == pytest.approx(0.5)
        assert decision_confidence([0.5, 0.5]) == pytest.approx(0.75)
        assert decision_confidence([1.0, 0.2]) == pytest.approx(1.0)

    def test_contradictions_discount(self) -> None:
        assert decision_confidence([0.8], [0.5]) == pytest.approx(0.4)
        assert decision_confidence([0.8], [1.0]) == 0.0

    def test_out_of_range_inputs_are_clamped(self) -> None:
        assert decision_confidence([2.0]) == 1.0
        assert decision_confidence([0.5], [-3.0]) == pytest.approx(0.5)


@pytest.mark.parametrize(
    ("edge_type", "expected"),
    [
        (EvidenceEdgeType.SUPPORTS, "memory supports decision"),
        (EvidenceEdgeType.CONTRADICTS, "memory contradicts decision"),
        (EvidenceEdgeType.DERIVED_FROM, "decision derived from memory"),
        (EvidenceEdgeType.RETRIEVED_FROM, "decision retrieved from memory"),
        (EvidenceEdgeType.GENERATED_BY, "decision generated by memory"),
        (EvidenceEdgeType.REFERENCES, "decision references memory"),
    ],
)
def test_phrase_reads_in_the_direction_of_each_type(
    edge_type: EvidenceEdgeType, expected: str
) -> None:
    assert phrase(edge_type, "memory", "decision") == expected


class TestTimeline:
    def test_orders_records_and_links_in_time(self) -> None:
        builder = GraphBuilder()
        document = builder.node("Policy", EvidenceNodeType.DOCUMENT)
        builder.node("Policy · Refunds", EvidenceNodeType.CHUNK)
        builder.node("Answer", EvidenceNodeType.DECISION)
        derived = builder.edge("Policy", "Policy · Refunds", EvidenceEdgeType.DERIVED_FROM)
        builder.edge("Policy · Refunds", "Answer")
        # The document existed long before it was first recorded as evidence.
        document.metadata_ = {"occurred_at": (EPOCH - timedelta(days=30)).isoformat()}

        events = timeline(builder.nodes.values(), builder.edges)

        assert [e.at for e in events] == sorted(e.at for e in events)
        assert events[0].id == document.id
        assert events[0].label == "document: Policy"
        edges = [e for e in events if e.kind is TimelineKind.EDGE]
        assert edges[0].id == derived.id
        assert edges[0].label == "Policy · Refunds derived from Policy"
        assert edges[1].label == "Policy · Refunds supports Answer"
        assert edges[0].source == "test"

    def test_records_precede_links_at_the_same_instant(self) -> None:
        builder = GraphBuilder()
        a = builder.node("a")
        builder.node("b")
        edge = builder.edge("a", "b")
        a.created_at = edge.observed_at
        events = [e for e in timeline([a], [edge]) if e.at == edge.observed_at]
        assert [e.kind for e in events] == [TimelineKind.NODE, TimelineKind.EDGE]

    def test_occurred_at_falls_back_to_created_at(self) -> None:
        builder = GraphBuilder()
        node = builder.node("a")
        assert occurred_at(node) == node.created_at
        node.metadata_ = {"occurred_at": "not a date"}
        assert occurred_at(node) == node.created_at
        node.metadata_ = {"occurred_at": "2026-01-01T00:00:00"}
        assert occurred_at(node) == datetime(2026, 1, 1, tzinfo=UTC)
