import uuid
from datetime import datetime
from enum import StrEnum

from sqlalchemy import CheckConstraint, Float, ForeignKey, Index, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from cortex_api.database.base import Base
from cortex_api.database.mixins import CreatedAtMixin, UUIDPrimaryKeyMixin
from cortex_api.database.types import string_enum


class EvidenceEdgeType(StrEnum):
    """How the upstream node relates to the downstream node.

    Edges always point from evidence to what it informed, so every type reads
    in one of two ways (`from` is upstream, `to` is downstream):

    - `supports`, `contradicts`: *from* supports / contradicts *to*.
    - `references`, `derived_from`, `retrieved_from`, `generated_by`:
      *to* references / was derived from / was retrieved from / was
      generated by *from*.
    """

    SUPPORTS = "supports"
    REFERENCES = "references"
    DERIVED_FROM = "derived_from"
    RETRIEVED_FROM = "retrieved_from"
    GENERATED_BY = "generated_by"
    CONTRADICTS = "contradicts"


class EvidenceEdge(UUIDPrimaryKeyMixin, CreatedAtMixin, Base):
    """A directed, attributed link between two evidence nodes.

    Every edge carries its provenance: how confident the link is, a
    human-readable explanation, the component that asserted it (`source`),
    and when the relationship was observed. Edges are append-only.
    """

    __tablename__ = "evidence_edges"

    organization_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("organizations.id", ondelete="CASCADE"), index=True
    )
    # Indexed by the leading column of the unique (from, to, type) index.
    from_node_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("evidence_nodes.id", ondelete="CASCADE")
    )
    to_node_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("evidence_nodes.id", ondelete="CASCADE"), index=True
    )
    type: Mapped[EvidenceEdgeType] = mapped_column(
        string_enum(EvidenceEdgeType, "evidence_edge_type", length=16)
    )
    confidence: Mapped[float] = mapped_column(Float)
    explanation: Mapped[str] = mapped_column(Text)
    source: Mapped[str] = mapped_column(String(255))
    observed_at: Mapped[datetime] = mapped_column(server_default=func.now())

    __table_args__ = (
        CheckConstraint("confidence >= 0 AND confidence <= 1", name="confidence_range"),
        CheckConstraint("length(btrim(explanation)) > 0", name="explanation_not_blank"),
        CheckConstraint("length(btrim(source)) > 0", name="source_not_blank"),
        CheckConstraint("from_node_id <> to_node_id", name="no_self_loop"),
        Index(
            "uq_evidence_edges_from_node_id_to_node_id_type",
            "from_node_id",
            "to_node_id",
            "type",
            unique=True,
        ),
    )

    def __repr__(self) -> str:
        return f"<EvidenceEdge {self.from_node_id} -{self.type}-> {self.to_node_id}>"
