import { expect, test } from "vitest";

import {
  clampDepth,
  COLUMN_WIDTH,
  confidenceOpacity,
  DEFAULT_DEPTH,
  describeEdge,
  displayMetadata,
  layoutEvidence,
  neighborsIn,
} from "@/lib/evidence";
import {
  CHUNK,
  CITED,
  DECISION,
  DOCUMENT,
  GRAPH,
  MEMORY,
  RECALLED,
  REPLIED,
  REPLY,
} from "@/test/evidence-fixtures";

test("lays evidence out left of the root and what it informed to the right", () => {
  const positions = new Map(layoutEvidence(GRAPH).map((p) => [p.node.id, p]));
  expect(positions.get(DECISION.id)).toMatchObject({ x: 0, y: 0 });
  expect(positions.get(DOCUMENT.id)?.x).toBe(-2 * COLUMN_WIDTH);
  expect(positions.get(REPLY.id)?.x).toBe(COLUMN_WIDTH);

  // Same column: chunks sort above memories, and the column centers on the root.
  const chunk = positions.get(CHUNK.id);
  const memory = positions.get(MEMORY.id);
  expect(chunk?.x).toBe(-COLUMN_WIDTH);
  expect(chunk!.y).toBeLessThan(memory!.y);
  expect(chunk!.y + memory!.y).toBe(0);
});

test("describes edges in their natural reading direction", () => {
  expect(describeEdge("supports", "Chunk", "Answer")).toBe("Chunk supports Answer");
  expect(describeEdge("derived_from", "Document", "Chunk")).toBe("Chunk derived from Document");
  expect(describeEdge("generated_by", "Answer", "Reply")).toBe("Reply generated by Answer");
});

test("finds neighbors in the loaded graph, strongest link first", () => {
  const { upstream, downstream } = neighborsIn(GRAPH, DECISION.id);
  expect(upstream.map((n) => n.edge.id)).toEqual([CITED.id, RECALLED.id]);
  expect(downstream.map((n) => n.edge.id)).toEqual([REPLIED.id]);
});

test("bounds depth and opacity", () => {
  expect(clampDepth(undefined)).toBe(DEFAULT_DEPTH);
  expect(clampDepth("abc")).toBe(DEFAULT_DEPTH);
  expect(clampDepth("0")).toBe(1);
  expect(clampDepth("99")).toBe(10);
  expect(confidenceOpacity(0)).toBeCloseTo(0.4);
  expect(confidenceOpacity(2)).toBe(1);
});

test("shows only flat metadata", () => {
  expect(
    displayMetadata({
      occurred_at: "x",
      model: "gpt-4.1",
      nested: { a: 1 },
      none: null,
      tokens: 3,
    }),
  ).toEqual([
    ["model", "gpt-4.1"],
    ["tokens", "3"],
  ]);
});
