import type {
  EvidenceEdge,
  EvidenceEdgeType,
  EvidenceGraph,
  EvidenceGraphNode,
  EvidenceNodeType,
} from "@celestra/cortex-sdk";

export const DEFAULT_DEPTH = 4;
export const MAX_DEPTH = 10;

export const NODE_TYPE_LABELS: Record<EvidenceNodeType, string> = {
  decision: "Decision",
  memory: "Memory",
  message: "Message",
  conversation: "Conversation",
  document: "Document",
  chunk: "Chunk",
  knowledge: "Knowledge",
  benchmark: "Model run",
};

/** Top-to-bottom order of node types within one column of the graph. */
const TYPE_ORDER: EvidenceNodeType[] = [
  "decision",
  "knowledge",
  "chunk",
  "document",
  "memory",
  "conversation",
  "message",
  "benchmark",
];

/**
 * Edges point from the evidence to what it informed. `supports` and
 * `contradicts` read forward; the rest read from the downstream end.
 */
const EDGE_VERBS: Record<EvidenceEdgeType, { verb: string; forward: boolean }> = {
  supports: { verb: "supports", forward: true },
  contradicts: { verb: "contradicts", forward: true },
  references: { verb: "references", forward: false },
  derived_from: { verb: "derived from", forward: false },
  retrieved_from: { verb: "retrieved from", forward: false },
  generated_by: { verb: "generated by", forward: false },
};

export function edgeVerb(type: EvidenceEdgeType): string {
  return EDGE_VERBS[type].verb;
}

/** "Refund policy supports Answer" or "Answer generated by Model run". */
export function describeEdge(type: EvidenceEdgeType, upstream: string, downstream: string): string {
  const { verb, forward } = EDGE_VERBS[type];
  return forward ? `${upstream} ${verb} ${downstream}` : `${downstream} ${verb} ${upstream}`;
}

export function clampDepth(value: string | undefined): number {
  const depth = Number.parseInt(value ?? "", 10);
  if (!Number.isFinite(depth)) return DEFAULT_DEPTH;
  return Math.min(MAX_DEPTH, Math.max(1, depth));
}

export function formatConfidence(value: number): string {
  return `${Math.round(value * 100)}%`;
}

export function formatTimestamp(iso: string): string {
  return new Date(iso).toLocaleString("en-US", {
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
    timeZone: "UTC",
  });
}

/** Fades weak evidence without making it unreadable. */
export function confidenceOpacity(value: number): number {
  return 0.4 + 0.6 * Math.min(1, Math.max(0, value));
}

export interface PositionedNode {
  node: EvidenceGraphNode;
  x: number;
  y: number;
}

export const COLUMN_WIDTH = 300;
export const ROW_HEIGHT = 104;

/**
 * Lays the graph out in columns by signed depth: evidence to the left of the
 * root, what the root informed to the right. Each column is centered on the
 * root's row and ordered by type, then by confidence.
 */
export function layoutEvidence(graph: EvidenceGraph): PositionedNode[] {
  const columns = new Map<number, EvidenceGraphNode[]>();
  for (const node of graph.nodes) {
    const column = columns.get(node.depth) ?? [];
    column.push(node);
    columns.set(node.depth, column);
  }
  const positioned: PositionedNode[] = [];
  for (const [depth, column] of columns) {
    column.sort(
      (a, b) =>
        TYPE_ORDER.indexOf(a.type) - TYPE_ORDER.indexOf(b.type) ||
        b.confidence - a.confidence ||
        a.title.localeCompare(b.title) ||
        a.id.localeCompare(b.id),
    );
    const top = -((column.length - 1) * ROW_HEIGHT) / 2;
    column.forEach((node, index) => {
      positioned.push({ node, x: depth * COLUMN_WIDTH, y: top + index * ROW_HEIGHT });
    });
  }
  return positioned;
}

export interface Neighbor {
  edge: EvidenceEdge;
  node: EvidenceGraphNode;
}

/** The node's direct neighbors within an already-loaded graph. */
export function neighborsIn(
  graph: EvidenceGraph,
  nodeId: string,
): { upstream: Neighbor[]; downstream: Neighbor[] } {
  const byId = new Map(graph.nodes.map((node) => [node.id, node]));
  const upstream: Neighbor[] = [];
  const downstream: Neighbor[] = [];
  for (const edge of graph.edges) {
    const from = byId.get(edge.from_node_id);
    const to = byId.get(edge.to_node_id);
    if (!from || !to) continue;
    if (edge.to_node_id === nodeId) upstream.push({ edge, node: from });
    if (edge.from_node_id === nodeId) downstream.push({ edge, node: to });
  }
  const strongest = (a: Neighbor, b: Neighbor) =>
    b.edge.provenance.confidence - a.edge.provenance.confidence;
  return { upstream: upstream.sort(strongest), downstream: downstream.sort(strongest) };
}

/** Plain metadata values worth showing an operator; nested objects are skipped. */
export function displayMetadata(metadata: Record<string, unknown>): [string, string][] {
  return Object.entries(metadata)
    .filter(([key, value]) => key !== "occurred_at" && value !== null && typeof value !== "object")
    .map(([key, value]) => [key, String(value)] as [string, string])
    .sort(([a], [b]) => a.localeCompare(b));
}
